#!/bin/bash
#
# Test wrapper run inside the VM

set -o nounset
set -o errexit
set -o errtrace

dmesg -n 7
echo 1 > /proc/sys/kernel/sysrq

ln -sf /sys/kernel/debug/tracing/ /root/t || true

# mount /var/log device if it exists
if [ -b /dev/disk/by-uuid/11111111-2222-3333-4444-555555555555 ] ; then
    systemctl stop rsyslog
    mount /dev/disk/by-uuid/11111111-2222-3333-4444-555555555555 /var/log
    systemctl start rsyslog
    mkdir -p /var/log/core
    echo 1 > /proc/sys/fs/suid_dumpable
    echo /var/log/core/core.%e.PID%p.SIG%s.TIME%t > /proc/sys/kernel/core_pattern
    ulimit -c unlimited
fi

# mounts dateras logging into directory shared with host
mkdir -p /var/log/datera
mount -t 9p -o trans=virtio logfs /var/log/datera

require-lib()
{
    . `basename "$1"`
}

require-bin()
{
    return 0
}

require-container()
{
    return 0
}

require-kernel-config()
{
    return 0
}

config-scratch-devs()
{
    return 0
}

config-mem()
{
    return 0
}

config-infiniband()
{
    return 0
}

config-vmcount()
{
    return 0
}

config-timeout()
{
    return 0
}

. rc.test

# We can't just do 'main || echo "TEST FAILED"' because
# 'set -o errexit' is disabled in the first half of a ||,
# and there is no way to re-enable it. However, ERR is
# inherited by subshells with 'set -o errtrace'.

trap 'echo -n "TEST " ; echo FAILED' ERR
# splitting this up makes sure that even if -x is enabled
# the magic string does not show up just because this line
# is executed.

main

exit 0
